export const LOCALIDADES = [
  "BELLA VISTA",
  "CAMPO HERRERA",
  "CHAÑARITO",
  "FAMAILLÁ",
  "LOS AGUIRRES",
  "LULES",
  "SAN PABLO",
];

export const TECNICOS = [
  "ACEVEDO GASTON",
  "AQUINO OMAR",
  "BARRIONUEVO MANUEL",
  "BLANCO JUAN PABLO",
  "CAROL SEBASTIAN",
  "FERNANDEZ MAURO",
  "GONZALEZ EMANUEL",
  "GONZALEZ SANTIAGO",
  "GUCHEA MIGUEL",
  "PEREZ EMANUEL",
  "RITTI JESUS",
  "ROBLES BRUNO",
  "VERA LEONEL",
];
